name: Node CI

on: [push]

jobs:

  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prettier
      uses: creyD/prettier_action@v4.2
      with:
        prettier_options: --write **/*.{tsx,ts,css}
        same_commit: true
      

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        username: ${{ secrets.REMOTE_USER }}
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd portfolio-next
          git pull
          npm install
          npm run build
          pm2 restart next
        
