name: Node CI

on: [push]

jobs:

  steps:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Prettier
      uses: creyD/prettier_action@v4.2
      with:
        prettier_options: --write **/*.{tsx,ts,css}
        commit_message: "🧹 prettier"
      

